In [ ]:
import numpy as np

# Task 1
empty_array = np.empty((2, 2))

# Task 2
ones_array = np.ones((4, 2))

# Task 3
shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)

# Task 4
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)

# Task 5
ones_like_array = np.ones_like(given_array)

# Task 6
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

empty_array, ones_array, filled_array, zeros_like_array, ones_like_array, numpy_array


(array([[4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]),
 array([[0, 0],
        [0, 0]]),
 array([[1, 1],
        [1, 1]]),
 array([1, 2, 3, 4]))

In [ ]:
import numpy as np

# Task 1
array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_to_49)

# Task 2
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# Task 3
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# Task 4
random_array_30 = np.random.random(30)
mean_of_array = random_array_30.mean()
print("\nRandom Array of size 30:\n", random_array_30)
print("Mean of the array:", mean_of_array)

# Task 5
random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print("\n10x10 Random Matrix:\n", random_matrix_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# Task 6
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element as 1:\n", zero_array)

# Task 7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\nReversed Array:\n", reversed_array)

# Task 8
rows, cols = 6, 6
border_array = np.ones((rows, cols))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

# Task 9
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("\n8x8 Checkerboard Matrix:\n", checkerboard_matrix)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.23785416 0.34218431 0.91385263 0.39783774 0.25681547 0.58426146
 0.23296747 0.21043048 0.45264369 0.96212082 0.89562273 0.8383565
 0.01663683 0.3122094  0.31156534 0.59942934 0.5607749  0.56901908
 0.21302607 0.06240186 0.32262894 0.70250731 0.87335862 0.56452211
 0.25739455 0.04024977 0.05188113 0.94098773 0.86507159 0.17010011]
Mean of the array: 0.4586237370697931

10x10 Random Matrix:
 [[0.55189909 0.12208943 0.05439312 0.9806392  0.38056644 0.05598378
  0.59391643 0.12611741 0.11179302 0.67183727]
 [0.25439232 0.3605049  0.25950043 0.69452044 0.78280708 0.71651302
  0.24374176 0.71043957 0.48555473 0.09706057]
 [0.64136542 0.61706418 0.74209042 0.37503476 0.30579727 0.024296
  0.899533

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1
array_addition = x + y
print("Addition of x and y:\n", array_addition)

# Task 2
array_subtraction = x - y
print("\nSubtraction of x and y:\n", array_subtraction)

# Task 3
array_multiplication = x * 3
print("\nMultiplication of x with 3:\n", array_multiplication)

# Task 4
array_square = np.square(x)
print("\nSquare of each element in x:\n", array_square)

# Task 5
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\nDot product of v and w:\n", dot_v_w)
print("Dot product of x and v:\n", dot_x_v)
print("Dot product of x and y:\n", dot_x_y)

# Task 6
concat_x_y = np.concatenate((x, y), axis=0)
concat_v_w = np.vstack((v, w))
print("\nConcatenation of x and y along rows:\n", concat_x_y)
print("Concatenation of v and w along columns:\n", concat_v_w)

# Task 7
try:
    concat_x_v = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_x_v = str(e)
print("\nConcatenation of x and v:\n", concat_x_v)
print("Explanation: Concatenation failed because x has shape (2, 2) and v has shape (2,). "
      "For concatenation along rows or columns, the dimensions must match.")


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w:
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Concatenation of x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Concatenation failed because x has shape (2, 2) and v has shape (2,). For concatenation along rows or columns, the dimensions must match.


In [ ]:
import numpy as np

# Arrays A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1 =\n", identity)
print("Verification: Is A * A^-1 equal to I?", np.allclose(identity, np.eye(2)))

# Task 2: Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =\n", AB)
print("BA =\n", BA)
print("Verification: Is AB equal to BA?", np.array_equal(AB, BA))

# Task 3: Prove (AB)^T = B^T A^T
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T =\n", AB_transpose)
print("B^T * A^T =\n", BT_AT)
print("Verification: Is (AB)^T equal to B^T A^T?", np.allclose(AB_transpose, BT_AT))

# Task 4: Solve system of linear equations using inverse methods
# Representing equations in matrix form: AX = B
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\nSolution to the linear equations using inverse method:")
print("X =", X)

# Alternative: Solve directly using np.linalg.solve
X_direct = np.linalg.solve(A_eq, B_eq)
print("\nSolution to the linear equations using np.linalg.solve:")
print("X =", X_direct)


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Verification: Is A * A^-1 equal to I? True

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Verification: Is AB equal to BA? False

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Verification: Is (AB)^T equal to B^T A^T? True

Solution to the linear equations using inverse method:
X = [ 2.  1. -2.]

Solution to the linear equations using np.linalg.solve:
X = [ 2.  1. -2.]


In [ ]:
import numpy as np
import time

# Task 1: Element-wise Addition
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
array1 = np.arange(size)
array2 = np.arange(size)

# Python Lists
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
time_list_add = time.time() - start_time

# NumPy Arrays
start_time = time.time()
array_addition = array1 + array2
time_array_add = time.time() - start_time

print(f"Element-wise addition:\nPython Lists: {time_list_add:.6f} seconds\nNumPy Arrays: {time_array_add:.6f} seconds")

# Task 2: Element-wise Multiplication
# Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
time_list_mul = time.time() - start_time

# NumPy Arrays
start_time = time.time()
array_multiplication = array1 * array2
time_array_mul = time.time() - start_time

print(f"\nElement-wise multiplication:\nPython Lists: {time_list_mul:.6f} seconds\nNumPy Arrays: {time_array_mul:.6f} seconds")

# Task 3: Dot Product
# Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
time_list_dot = time.time() - start_time

# NumPy Arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
time_array_dot = time.time() - start_time

print(f"\nDot product:\nPython Lists: {time_list_dot:.6f} seconds\nNumPy Arrays: {time_array_dot:.6f} seconds")

# Task 4: Matrix Multiplication
matrix_size = 1000
list_matrix1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
array_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
array_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

# Python Lists
start_time = time.time()
list_matrix_mult = [
    [sum(list_matrix1[i][k] * list_matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)]
    for i in range(matrix_size)
]
time_list_matrix_mult = time.time() - start_time

# NumPy Arrays
start_time = time.time()
array_matrix_mult = np.dot(array_matrix1, array_matrix2)
time_array_matrix_mult = time.time() - start_time

print(f"\nMatrix multiplication:\nPython Lists: {time_list_matrix_mult:.6f} seconds\nNumPy Arrays: {time_array_matrix_mult:.6f} seconds")


Element-wise addition:
Python Lists: 0.178071 seconds
NumPy Arrays: 0.004087 seconds

Element-wise multiplication:
Python Lists: 0.168438 seconds
NumPy Arrays: 0.004011 seconds

Dot product:
Python Lists: 0.158003 seconds
NumPy Arrays: 0.002015 seconds

Matrix multiplication:
Python Lists: 240.216372 seconds
NumPy Arrays: 1.292692 seconds
